sudo: require
services:
    - docker
    
before_install:
    - docker build -t kadamone/docker-react -f Dockerfile.dev .
    
script:
    - docker run kadamone/docker-react npm run test -- --coverage